Dicionarios datasets
ImpulsoGov/coronacidades-datasource pull request #21
Opened 2020-05-20 23:47 UTC by francisconog

#20

2020-06-16 23:30 UTC, francisconog commented
#54

2020-06-22 16:51 UTC, fernandascovino requested changes

2020-06-22 16:51 UTC, fernandascovino commented on Makefile
> +		-p 80:80 \
essa mudança não é necessária para o dicionário, não?

2020-06-22 16:51 UTC, fernandascovino commented on src/loader/endpoints/get_cases.py
> +    "max(confirmed_cases) != max(date)": lambda df: all(
porque tem essas mudanças aqui?

2020-06-22 16:51 UTC, fernandascovino commented on src/loader/endpoints/get_health.py
> +    "more ventilators than beds": lambda df: len(df[df['number_ventilators'].values > df['number_beds'].values]) == 0,
e essas aqui?

2020-06-22 18:46 UTC, francisconog commented on Makefile
> +		-p 80:80 \
É nn. Isso é pq eu tive que mudar de porta pra poder rodar aqui pq a porta 7000 já tava ocupada

2020-06-22 18:49 UTC, francisconog commented on src/loader/endpoints/get_cases.py
> +    "max(confirmed_cases) != max(date)": lambda df: all(
Esse teste tava todo comentado, achei que fosse assim pq tava incompleto, ai fiz como eu achei melhor.

2020-06-22 18:51 UTC, francisconog commented on src/loader/endpoints/get_health.py
> +    "more ventilators than beds": lambda df: len(df[df['number_ventilators'].values > df['number_beds'].values]) == 0,
A primeira foi o teste pra ver se tinha mais ventiladores que leitos e a outra foi só organização msm

2020-06-22 18:55 UTC, fernandascovino commented on src/loader/endpoints/get_cases.py
> +    "max(confirmed_cases) != max(date)": lambda df: all(
remove essa modificação do PR por favor ;)

2020-06-22 18:55 UTC, fernandascovino commented on src/loader/endpoints/get_health.py
> +    "more ventilators than beds": lambda df: len(df[df['number_ventilators'].values > df['number_beds'].values]) == 0,
remove essa modificação do PR por favor ;)

2020-06-22 19:12 UTC, fernandascovino commented on src/loader/endpoints/get_cases.py
> +    "max(confirmed_cases) != max(date)": lambda df: all(
eu vou deixar essas mudanças aqui comentadas para testar no outro PR

2020-06-22 19:13 UTC, fernandascovino commented on src/loader/endpoints/get_health.py
> +    "more ventilators than beds": lambda df: len(df[df['number_ventilators'].values > df['number_beds'].values]) == 0,
esse teste aqui por exemplo não entra, segundo nosso doc...

2020-06-22 19:15 UTC, fernandascovino commented on src/loader/endpoints/get_cases.py
> +    # TODO: test it before update to master
@francisconog deixei aqui comentado, para ver isso no PR de testes

2020-06-25 18:35 UTC, merged